### ISSUE TITLE
Logo spacing and weight

### ISSUE THREAD

**Issue by KeenanLukeOM** [DXgovernance/infinite-hackathon#10]
I am currently on a QHD//1440p monitor. This issue is being opened after the update correcting the resolution-related scaling.

![image](https://user-images.githubusercontent.com/76129769/186496359-2df9e9b7-bc53-4496-969f-3bea2e3823ae.png)
Currently, the implementation has a reduced border on the primary logo; it is also roughly 1.5x the size of the other header buttons, while it should be roughly 2.5x.

![image](https://user-images.githubusercontent.com/76129769/186496697-d265b2e6-fd0f-4248-8c8a-c5ecf93ca6cb.png)
Intended visualization

**Comment by rulfo71** [comment]
I took the image from the figma so if there is too much space we can just change te image
