### ISSUE TITLE
Genesis background dynamic scrolling and dimming

### ISSUE THREAD

**Issue by KeenanLukeOM** [DXgovernance/infinite-hackathon#16]
![image](https://user-images.githubusercontent.com/76129769/186515945-a776cfd6-8ab0-432a-9113-30a6b42f75ea.png)
The background image on the Genesis page should follow the user down the page. If the image slightly lagged behind the users scroll smoothly by about 0.5 seconds it would be perfect, but locking to the monitor is also okay for the MVP. It should also dim as the user scrolls down the page, to be completely removed by the `Do you have what it takes to tame the infinite?` section.

![image](https://user-images.githubusercontent.com/76129769/186516312-b02bb84d-6753-4bd4-b954-d36023442f02.png)
Visualization of intended behavior. Can provide a closer look as needed.

**Comment by rulfo71** [comment]
I think locking to the monitor for MVP would be good for now, so we get to deploy a version and then getting it better, thinking on baby steps but whatever you think is better

**Comment by KeenanLukeOM** [comment]
Agreed on locking to monitor for MVP release, keeping this ticket open for future use.
