### ISSUE TITLE
Primary Landing Adjustments

### ISSUE THREAD

**Issue by KeenanLukeOM** [DXgovernance/infinite-hackathon#21]
Further adjustments to the primary landing section from INTBLUE can be found below. The current [implementation on staging](https://dxgovernance.github.io/infinite-hackathon/#/) can be found on the right, with the proposed changes/initial implementations for reference on the right.

![image](https://user-images.githubusercontent.com/76129769/188248496-391999e0-f21e-4546-a55f-494e8974b38c.png)

- [ ] LOGO: distance between "logotype" and surrounding black box. 

- [ ] TYPOGRAPHY: check type (is this the right cut? it looks a bit thin), type height, line height, spacing (everything is a bit off) 

- [ ] "LEARN MORE" BUTTON: Whitespace/typography ratio. 

- [ ] INFINITE MANIFESTO: wen fading animation on scroll ser? (We had discussed moving this back in priority, and can focus after other main tasks are complete)

- [ ] MARGINS: a bit more space on the right and the left would be great! 

- [ ] MENU: the button outline is very thin, 1px bigger please. 

- [ ] BACKGROUND: parallax animation as sketched out in the Figma file (I'm happy to explain how it should work if it's not clear) 

I've attached relevant updated images below:

![Group 48095938](https://user-images.githubusercontent.com/76129769/188248564-fc5afaf9-e108-407b-ba5d-8beceb53147a.png)

If there are any questions surrounding the above changes, please reach out to myself on Keybase or leave a comment here. Ticket #11 covers specifics of the text as found in the above Figma file.

**Comment by rulfo71** [comment]
" BACKGROUND: parallax animation as sketched out in the Figma file (I'm happy to explain how it should work if it's not clear)"

parallax animation until organizers right? I mean, organizers with a black background?

**Comment by rulfo71** [comment]
I already add a pixel to the button outline but here is the image, feel free to add as much as you consider 
![burger-button2](https://user-images.githubusercontent.com/5303411/188716806-e9109e92-649f-40cf-bce9-4f9750c8e27f.png)
