### ISSUE TITLE
Primary Organizer Section Adjustments

### ISSUE THREAD

**Issue by KeenanLukeOM** [DXgovernance/infinite-hackathon#22]
Further adjustments to the primary Organizer section from INTBLUE can be found below. The current [implementation on staging](https://dxgovernance.github.io/infinite-hackathon/#/) can be found on the right, with the proposed changes/initial implementations for reference on the right.

![image](https://user-images.githubusercontent.com/76129769/188248779-cc6d9ea5-a761-428d-93a2-801ca421dcc7.png)

TABLE: The whole thing is a bit all over the place. Please check the details: 
- [ ] typography sizes (headline, inside the table...), 
- [ ] Logo size. 
- [ ] The line around the plus sign looks a bit thin, 1px more, please  

Figma for reference: https://www.figma.com/file/Au0PXawZA9FXpgBPI5JMFf/hackersoul-microsite?node-id=381%3A4677

These changes should be reflected on both the primary page AND the Genesis page.

If there are any questions surrounding the above changes, please reach out to myself on Keybase or leave a comment here.

**Comment by rulfo71** [comment]
for the line around the plus i'm using the image attached 
are you able to get it thicker? 
![join](https://user-images.githubusercontent.com/5303411/188654310-4f0de0a2-445c-43b2-aa68-6934bec4dea7.png)
