### ISSUE TITLE
Genesis CTA Cards Adjustments

### ISSUE THREAD

**Issue by KeenanLukeOM** [DXgovernance/infinite-hackathon#25]
Further adjustments to the primary landing section from INTBLUE can be found below. The current [implementation on staging](https://dxgovernance.github.io/infinite-hackathon/#/) can be found on the right, with the proposed changes/initial implementations for reference on the right.

![image](https://user-images.githubusercontent.com/76129769/188249150-4d6f5ccc-33a8-4e10-bbdf-7a0d6426c2dd.png)

- [ ] DETAILS:  table alignment is all over the place 
- [ ] DETAILS IN THE INFO CARD: lines, typography, alignment, missing learn more for public judging, etc. 
- [ ] BACKGROUND: Sticky image in the back 

Figma for reference: https://www.figma.com/file/Au0PXawZA9FXpgBPI5JMFf/hackersoul-microsite?node-id=381%3A4677

If there are any questions surrounding the above changes, please reach out to myself on Keybase or leave a comment here.

**Comment by rulfo71** [comment]
about the "Learn more" we took it away because we didn't have where to link it to and it wasn't good that it looked like a link but you couldn't press ion t.

**Comment by KeenanLukeOM** [comment]
The action buttons at the bottom of each card aren't present in the live build:

![image](https://user-images.githubusercontent.com/76129769/192318060-4554e10f-22bb-4dba-959a-19b5dbb931ac.png)

vs

![image](https://user-images.githubusercontent.com/76129769/192318135-965c5abe-4edb-48f3-ae4f-9c4b53c2ac62.png)

**Comment by rulfo71** [comment]
i'm not sure i understand what you mean here. the links on the footer of each info box are not working? i tried them and they are working for me, except the middle one we took away.

**Comment by KeenanLukeOM** [comment]
Apologies, missed the fact that we removed this in my notes when was running through the tickets!
