### ISSUE TITLE
Add extra block of text

### ISSUE THREAD

**Issue by KeenanLukeOM** [DXgovernance/infinite-hackathon#33]
An extra text block is needed on the Genesis page. 

![image](https://user-images.githubusercontent.com/76129769/191634749-3aa2318b-5d4d-4b13-aae7-65a0a67e48e3.png)

**A variety of incentives.**

There are _infinite_ reasons to join Infinite hackathons. Participation in the genesis event grants hackers access to travel grants, hacker house accommodation, token prizes, and much more.  Learn how to become eligible at the [Infinite Discord](https://discord.gg/sqrHkJgA2w)!

**Comment by rulfo71** [comment]
![image](https://user-images.githubusercontent.com/5303411/191742308-8534a9ed-3cba-4042-bd52-b9a43bddbc5a.png)

@KeenanLukeOM  looks good? i mean the underline for the infinte discord, or would  you like the text color to be blue?
