### ISSUE TITLE
Button sizing standardization and spacing

### ISSUE THREAD

**Issue by KeenanLukeOM** [DXgovernance/infinite-hackathon#36]
The primary buttons should be of similar dimensions and should be displayed left to right. If Int_blue has advised otherwise, ignore this issue.

![image](https://user-images.githubusercontent.com/76129769/191636414-16f84242-f03a-45e5-b74f-0336266e6ae7.png)

**Comment by rulfo71** [comment]
@KeenanLukeOM 
similar dimensions would be something like this: 
![image](https://user-images.githubusercontent.com/5303411/191967347-ccfaaee6-5d3c-4ab7-a960-4a0f60f3dffe.png)

or align to the center would be this: 
![image](https://user-images.githubusercontent.com/5303411/191967779-c5276295-dba5-4334-994f-dfd26f243b0a.png)


each one with its width would be this: 
![image](https://user-images.githubusercontent.com/5303411/191967541-a7d69122-5a77-42c1-b2d6-7797aa3719ff.png)

i think it looks better the last option,, each one with its width but let me know what you think

**Comment by KeenanLukeOM** [comment]
I agree that the bottom one looks best. I also think IntBlue mentioned not wanting the date in a button, did you two end up having a sync?

**Comment by rulfo71** [comment]
yes, he told me he was going to work on the design. 
meanwhile i wanted to have something that looks nice, in case he doesn't have it yet
