### ISSUE TITLE
Add Swarm as a co-organizer on Main and Genesis pages

### ISSUE THREAD

**Issue by KeenanLukeOM** [DXgovernance/infinite-hackathon#38]
![image](https://user-images.githubusercontent.com/76129769/192002896-5f223237-2482-4bfa-aab5-9205fd1db64d.png)

Introduce Swarm between "Kleros" and "Join us".

Information from left to right:

**Icon:** 
![swarm](https://user-images.githubusercontent.com/76129769/192003094-5a37fe0b-cfea-407c-8ad2-5fda7b982fb2.png)

**Name:** 
SWARM ASSN

**Title:**
GENESIS CO-ORGANIZER

**Tag:**
DATA STORAGE CHAMPIONS

**Comment by rulfo71** [comment]
i'm missing the url, i'll add https://www.ethswarm.org/

**Comment by KeenanLukeOM** [comment]
Made a slight adjustment to the "Name" field as a response from the Swapr association team

It should now read "SWARM ASSN"
